/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found. It
 * should not be modified by hand.
 */

package in.gov.jharkhand.safetyar;

public final class R {
  public static final class color {
    public static final int accent_gold=0x7f010000;
    public static final int accent_orange=0x7f010001;
    public static final int ar_cyan=0x7f010002;
    public static final int ar_guidance_green=0x7f010003;
    public static final int ar_hud_bg=0x7f010004;
    public static final int ar_laser_red=0x7f010005;
    public static final int bg_card=0x7f010006;
    public static final int bg_card_border=0x7f010007;
    public static final int bg_card_elevated=0x7f010008;
    public static final int bg_dark=0x7f010009;
    public static final int black=0x7f01000a;
    public static final int error=0x7f01000b;
    public static final int error_bg=0x7f01000c;
    public static final int info=0x7f01000d;
    public static final int primary=0x7f01000e;
    public static final int primary_dark=0x7f01000f;
    public static final int primary_light=0x7f010010;
    public static final int success=0x7f010011;
    public static final int success_bg=0x7f010012;
    public static final int text_muted=0x7f010013;
    public static final int text_primary=0x7f010014;
    public static final int text_secondary=0x7f010015;
    public static final int transparent=0x7f010016;
    public static final int warning=0x7f010017;
    public static final int white=0x7f010018;
  }
  public static final class drawable {
    public static final int app_logo=0x7f020000;
    public static final int badge_active_green=0x7f020001;
    public static final int badge_verified=0x7f020002;
    public static final int bg_gradient_dark=0x7f020003;
    public static final int btn_demo=0x7f020004;
    public static final int btn_lang_dropdown=0x7f020005;
    public static final int btn_login_yellow=0x7f020006;
    public static final int btn_primary=0x7f020007;
    public static final int card_bg=0x7f020008;
    public static final int card_bg_accent=0x7f020009;
    public static final int card_blue=0x7f02000a;
    public static final int card_green=0x7f02000b;
    public static final int card_login_dark=0x7f02000c;
    public static final int card_orange=0x7f02000d;
    public static final int card_purple=0x7f02000e;
    public static final int card_red=0x7f02000f;
    public static final int card_teal=0x7f020010;
    public static final int fire_scene=0x7f020011;
    public static final int gas_scene=0x7f020012;
    public static final int input_box_dark=0x7f020013;
    public static final int raju_avatar=0x7f020014;
  }
  public static final class mipmap {
    public static final int ic_launcher=0x7f030000;
    public static final int ic_launcher_round=0x7f030001;
  }
  public static final class string {
    public static final int app_name=0x7f040000;
    public static final int app_subtitle=0x7f040001;
    public static final int ar_hazard_detected=0x7f040002;
    public static final int ar_safe_zone=0x7f040003;
    public static final int ar_tracking_ready=0x7f040004;
    /**
     * AR HUD
     */
    public static final int ar_tracking_searching=0x7f040005;
    /**
     * Common Actions
     */
    public static final int btn_continue=0x7f040006;
    public static final int btn_demo_login=0x7f040007;
    public static final int btn_download_cert=0x7f040008;
    public static final int btn_login=0x7f040009;
    public static final int btn_start_ar=0x7f04000a;
    public static final int btn_start_quiz=0x7f04000b;
    public static final int btn_sync_now=0x7f04000c;
    public static final int btn_verify_qr=0x7f04000d;
    public static final int govt_tagline=0x7f04000e;
    public static final int lang_english=0x7f04000f;
    /**
     * Languages
     */
    public static final int lang_hindi=0x7f040010;
    public static final int lang_santali=0x7f040011;
    public static final int nav_certificates=0x7f040012;
    /**
     * Navigation
     */
    public static final int nav_home=0x7f040013;
    public static final int nav_profile=0x7f040014;
    public static final int nav_training=0x7f040015;
    public static final int nav_videos=0x7f040016;
    /**
     * Auth
     */
    public static final int worker_id_hint=0x7f040017;
  }
  public static final class style {
    public static final int Theme_JHSafetyAR=0x7f050000;
    public static final int Theme_JHSafetyAR_Fullscreen=0x7f050001;
  }
}